export const authContants = {
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAIL: "LOGIN_FAIL",
  LOGOUT_REQUEST: "LOGOUT_REQUEST",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  LOGOUT_FAIL: "LOGOUT_FAIL",

};

export const userContants = {
  SIGNUP_REQUEST: "SIGNUP_REQUEST",
  SIGNUP_SUCCESS: "SIGNUP_SUCCESS",
  SIGNUP_FAIL: "SIGNUP_FAIL",
}

export const categoryContants = {
  GETALLCATE_REQUEST: "GETALLCATE_REQUEST",
  GETALLCATE_SUCCESS: "GETALLCATE_SUCCESS",
  GETALLCATE_FAIL: "GETALLCATE_FAIL",
  ADDCATE_REQUEST: "ADDCATE_REQUEST",
  ADDCATE_SUCCESS: "ADDCATE_SUCCESS",
  ADDCATE_FAIL: "ADDCATE_FAIL",
}

export const productContants = {
  ADDPRODUCT_REQUEST: "ADDPRODUCT_REQUEST",
  ADDPRODUCT_SUCCESS: "ADDPRODUCT_SUCCESS",
  ADDPRODUCT_FAIL: "ADDPRODUCT_FAIL",
}